export const ROUTES = {
	home: 'ru?/',
	aboutUs: 'ru?/about-us',
	shipment: 'ru?/shipment',
	payment: 'ru?/payment',
	contacts: 'ru?/contacts',
	guaranteeAndRefund: 'ru?/guarantee-and-refund',
	publicOffer: 'ru?/public-offer',
	catalog: 'ru?/catalog/:section/*',
	product: 'ru?/*',
	bookmarks: 'ru?/bookmarks/',
	comparison: 'ru?/comparison/',
	cart: 'ru?/cart/',
	order: 'ru?/order/',
	successful: 'ru?/order/successful/*',
	tyreDiskSizeCalc: 'ru?/tyre-disk-size-calc/',
	search: 'ru?/search/',
	page: 'ru?/page/*',
	flushCache: 'ru?/api/flush-cache',
};
